# coding: utf-8

"""
    DSMF

    A simple API to interact with the Domain Slice Management Function. Supports reserving, creating and removing slices and tunnels from one external domain to another external domain or host. Please refer to the topology drawings for further information about the network structures.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from dsmf_client.paths.tunnel_deployment.delete import TunnelDeploymentDelete
from dsmf_client.paths.tunnel_deployment.get import TunnelDeploymentGet
from dsmf_client.paths.tunnel_deployment.put import TunnelDeploymentPut


class TunnelManagementApi(
    TunnelDeploymentDelete,
    TunnelDeploymentGet,
    TunnelDeploymentPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
