# coding: utf-8

"""
    Jump Host API

    A simple API to manage tunnel entries and exits on a dedicated jump host.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from jump_host_client.paths.auth.put import AuthPut


class AuthenticationApi(
    AuthPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
