version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/controller/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/dsmf/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/dsmf/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/esmf/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/esmf/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/host/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/host/adversary"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/switch/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/switch/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/vpn_gateway/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/vpn_gateway/server"
    schedule:
      interval: "daily"
