# coding: utf-8

# flake8: noqa

"""
    VPN Gateway API

    A simple API to manage tunnel entries on a dedicated host within the edges. The VPN Gateway is used to encrypt traffic before it enters the first black network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from vpn_gateway_client.api_client import ApiClient

# import Configuration
from vpn_gateway_client.configuration import Configuration

# import exceptions
from vpn_gateway_client.exceptions import OpenApiException
from vpn_gateway_client.exceptions import ApiAttributeError
from vpn_gateway_client.exceptions import ApiTypeError
from vpn_gateway_client.exceptions import ApiValueError
from vpn_gateway_client.exceptions import ApiKeyError
from vpn_gateway_client.exceptions import ApiException
