# coding: utf-8

# flake8: noqa

"""
    Jump Host API

    A simple API to manage tunnel entries and exits on a dedicated jump host.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from jump_host_client.api_client import ApiClient

# import Configuration
from jump_host_client.configuration import Configuration

# import exceptions
from jump_host_client.exceptions import OpenApiException
from jump_host_client.exceptions import ApiAttributeError
from jump_host_client.exceptions import ApiTypeError
from jump_host_client.exceptions import ApiValueError
from jump_host_client.exceptions import ApiKeyError
from jump_host_client.exceptions import ApiException
