# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest

from esmf_client import configuration, api_client
from esmf_client.paths.slice import delete  # noqa: E501

from .. import ApiTestMixin


class TestSlice(ApiTestMixin, unittest.TestCase):
    """
    Slice unit test stubs
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
