openapi: 3.0.3
info:
  description: "A simple API to interact with the Domain Slice Management Function.\
    \ Supports reserving, creating and removing slices and tunnels from one external\
    \ domain to another external domain or host. Please refer to the topology drawings\
    \ for further information about the network structures."
  title: DSMF
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /auth:
    description: Endpoint to manage authentication tokens
    put:
      description: "Issues a new authentication token in exchange for credentials.\
        \ Currently requires no credentials, this is up to future implementations."
      operationId: auth_put
      parameters: [ ]
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: The authentication token as string
        "403":
          description: Wrong credentials were specified
      tags:
        - Authentication
      x-openapi-router-controller: dsmf_server.controllers.authentication_controller
    summary: Manages authentication towards this service
  /slice_deployment:
    delete:
      description: Deletes a slice
      operationId: slice_deployment_delete
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The id of the slice to be deleted.
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        "200":
          description: The slice was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The slice could not be found.
      tags:
        - Slice Management
      x-openapi-router-controller: dsmf_server.controllers.slice_management_controller
    description: Endpoint to manage slices
    get:
      description: Lists all current slices
      operationId: slice_deployment_get
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/slice'
                type: array
          description: The current list of slices
        "403":
          description: Invalid authentication provided
      tags:
        - Slice Management
      x-openapi-router-controller: dsmf_server.controllers.slice_management_controller
    put:
      description: Creates a new slice from a reservation
      operationId: slice_deployment_put
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The slice to create from the corresponding reservation id
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        "200":
          description: The slice has been created
        "403":
          description: Invalid authentication provided
        "404":
          description: The slice reservation could not be found.
        "500":
          description: The deployment to the network failed
      tags:
        - Slice Management
      x-openapi-router-controller: dsmf_server.controllers.slice_management_controller
    summary: Manages slices on the current domain
  /slice_reservation:
    delete:
      description: Deletes a slice reservation
      operationId: slice_reservation_delete
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The id of the slice reservation to be deleted.
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        "200":
          description: The slice reservation was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The slice reservation could not be found.
      tags:
        - Slice Reservation
      x-openapi-router-controller: dsmf_server.controllers.slice_reservation_controller
    description: Endpoint to manage slice reservations
    get:
      description: Lists all current slice reservations
      operationId: slice_reservation_get
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/slice'
                type: array
          description: The current list of slice reservations
        "403":
          description: Invalid authentication provided
      tags:
        - Slice Reservation
      x-openapi-router-controller: dsmf_server.controllers.slice_reservation_controller
    put:
      description: Creates a new slice reservation
      operationId: slice_reservation_put
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The slice to reserve. Will check for issues.
          explode: true
          in: query
          name: slice
          required: true
          schema:
            $ref: '#/components/schemas/slice'
          style: form
      responses:
        "200":
          description: The slice has been reserved
        "403":
          description: Invalid authentication provided
        "404":
          description: The input or output could not be found
        "409":
          description: A slice with this id is already known
        "507":
          description: Insufficient resources
      tags:
        - Slice Reservation
      x-openapi-router-controller: dsmf_server.controllers.slice_reservation_controller
    summary: Manages slice reservations on the current domain
  /tunnel_deployment:
    delete:
      description: Deletes a tunnel
      operationId: tunnel_deployment_delete
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The id of the tunnel to be deleted.
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        "200":
          description: The tunnel was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The tunnel could not be found.
      tags:
        - Tunnel Management
      x-openapi-router-controller: dsmf_server.controllers.tunnel_management_controller
    description: Endpoint to manage tunnels
    get:
      description: Lists all current tunnels
      operationId: tunnel_deployment_get
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tunnel'
                type: array
          description: The current list of tunnels
        "403":
          description: Invalid authentication provided
      tags:
        - Tunnel Management
      x-openapi-router-controller: dsmf_server.controllers.tunnel_management_controller
    put:
      description: Creates a new tunnel or modifies a tunnel from a reservation
      operationId: tunnel_deployment_put
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The tunnel to create from the corresponding reservation id
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        "200":
          description: The tunnel has been created
        "403":
          description: Invalid authentication provided
        "404":
          description: The tunnel reservation could not be found.
        "500":
          description: The deployment to the network failed
      tags:
        - Tunnel Management
      x-openapi-router-controller: dsmf_server.controllers.tunnel_management_controller
    summary: Manages tunnels on the current domain
  /tunnel_reservation:
    delete:
      description: Deletes a tunnel reservation
      operationId: tunnel_reservation_delete
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The id of the tunnel reservation to be deleted.
          explode: true
          in: query
          name: id
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        "200":
          description: The tunnel reservation was successfully deleted.
        "403":
          description: Invalid authentication provided.
        "404":
          description: The tunnel reservation could not be found.
      tags:
        - Tunnel Reservation
      x-openapi-router-controller: dsmf_server.controllers.tunnel_reservation_controller
    description: Endpoint to manage tunnel reservations
    get:
      description: Lists all current tunnel reservations
      operationId: tunnel_reservation_get
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tunnel'
                type: array
          description: The current list of tunnel reservations
        "403":
          description: Invalid authentication provided
      tags:
        - Tunnel Reservation
      x-openapi-router-controller: dsmf_server.controllers.tunnel_reservation_controller
    put:
      description: "Creates a new tunnel reservation or stages changes to an existing\
        \ deployed tunnel, as long as source and target of the tunnel match."
      operationId: tunnel_reservation_put
      parameters:
        - description: The authentication token issued by prior login
          explode: true
          in: query
          name: auth
          required: true
          schema:
            type: string
          style: form
        - description: The tunnel to reserve. Will check for issues.
          explode: true
          in: query
          name: tunnel
          required: true
          schema:
            $ref: '#/components/schemas/tunnel'
          style: form
      responses:
        "200":
          description: The tunnel has been reserved
        "403":
          description: Invalid authentication provided
        "404":
          description: The input or output could not be found
        "409":
          description: A tunnel with this id is already known and does not match current
            source and target
        "507":
          description: Insufficient resources
      tags:
        - Tunnel Reservation
      x-openapi-router-controller: dsmf_server.controllers.tunnel_reservation_controller
    summary: Manages tunnel reservations on the current domain
components:
  schemas:
    slice:
      example:
        rate: 6
        latency: 1
        from: from
        id: 0
        to: to
      properties:
        id:
          description: The slice identifier
          format: int32
          title: id
          type: integer
        rate:
          description: The transmission rate as bits/s
          format: int64
          title: rate
          type: integer
        latency:
          description: The required maximum latency
          format: int16
          title: latency
          type: integer
        from:
          description: The name of the input domain or host
          title: from
          type: string
        to:
          description: The name of the output domain or host
          title: to
          type: string
      title: slice
      type: object
    tunnel:
      example:
        rate: 6
        latency: 1
        from: from
        id: 0
        to: to
      properties:
        id:
          description: The tunnel identifier
          format: int32
          title: id
          type: integer
        rate:
          description: The transmission rate as bits/s
          format: int64
          title: rate
          type: integer
        latency:
          description: The required maximum latency
          format: int16
          title: latency
          type: integer
        from:
          description: The name of the input domain or host
          title: from
          type: string
        to:
          description: The name of the output domain or host
          title: to
          type: string
      title: tunnel
      type: object
