# coding: utf-8

"""
    DSMF

    A simple API to interact with the Domain Slice Management Function. Supports reserving, creating and removing slices and tunnels from one external domain to another external domain or host. Please refer to the topology drawings for further information about the network structures.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from dsmf_client import schemas  # noqa: F401


class NetworkBorderConfiguration(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    A network border configuration element (telling us where to route traffic to when wanting to reach a different network)
    """


    class MetaOapg:
        
        class properties:
            network_name = schemas.StrSchema
            device_name = schemas.StrSchema
        
            @staticmethod
            def connection() -> typing.Type['ConnectionConfiguration']:
                return ConnectionConfiguration
            __annotations__ = {
                "network_name": network_name,
                "device_name": device_name,
                "connection": connection,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["network_name"]) -> MetaOapg.properties.network_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["device_name"]) -> MetaOapg.properties.device_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connection"]) -> 'ConnectionConfiguration': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["network_name", "device_name", "connection", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["network_name"]) -> typing.Union[MetaOapg.properties.network_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["device_name"]) -> typing.Union[MetaOapg.properties.device_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connection"]) -> typing.Union['ConnectionConfiguration', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["network_name", "device_name", "connection", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        network_name: typing.Union[MetaOapg.properties.network_name, str, schemas.Unset] = schemas.unset,
        device_name: typing.Union[MetaOapg.properties.device_name, str, schemas.Unset] = schemas.unset,
        connection: typing.Union['ConnectionConfiguration', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'NetworkBorderConfiguration':
        return super().__new__(
            cls,
            *_args,
            network_name=network_name,
            device_name=device_name,
            connection=connection,
            _configuration=_configuration,
            **kwargs,
        )

from dsmf_client.model.connection_configuration import ConnectionConfiguration
