# coding: utf-8

"""
    CTMF

    A simple API to interact with the Core Tunnel Management Function. Supports creating and removing tunnels on this domains. Is advised to allocate resources by external ESMFs. The CTMF is a subset of the ESMF. Please refer to the topology drawings for further information about the network structures.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from ctmf_client.paths.tunnel_deployment.delete import TunnelDeploymentDelete
from ctmf_client.paths.tunnel_deployment.get import TunnelDeploymentGet
from ctmf_client.paths.tunnel_deployment.put import TunnelDeploymentPut
from ctmf_client.paths.tunnel_reservation.delete import TunnelReservationDelete
from ctmf_client.paths.tunnel_reservation.get import TunnelReservationGet
from ctmf_client.paths.tunnel_reservation.put import TunnelReservationPut


class TunnelSynchronizationApi(
    TunnelDeploymentDelete,
    TunnelDeploymentGet,
    TunnelDeploymentPut,
    TunnelReservationDelete,
    TunnelReservationGet,
    TunnelReservationPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
