# coding: utf-8

"""
    Jump Host API

    A simple API to manage tunnel entries and exits on a dedicated jump host.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import jump_host_client
from jump_host_client.model.tunnel_entry import TunnelEntry
from jump_host_client import configuration


class TestTunnelEntry(unittest.TestCase):
    """TunnelEntry unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
