# coding: utf-8

# flake8: noqa

"""
    DTMF

    A simple API to interact with the Domain Tunnel Management Function. Supports reserving, creating and removing tunnels from one external domain to another external domain. This service does not create tunnel endpoints, but reserves resources instead in the current domain instead. The DTMF is a subset of the DSMF. Please refer to the topology drawings for further information about the network structures.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from dtmf_client.api_client import ApiClient

# import Configuration
from dtmf_client.configuration import Configuration

# import exceptions
from dtmf_client.exceptions import OpenApiException
from dtmf_client.exceptions import ApiAttributeError
from dtmf_client.exceptions import ApiTypeError
from dtmf_client.exceptions import ApiValueError
from dtmf_client.exceptions import ApiKeyError
from dtmf_client.exceptions import ApiException
