openapi: 3.0.3
info:
  description: A simple API to interact with the Core Tunnel Management Function.
    Supports creating and removing tunnels on this domains. Is advised to allocate
    resources by external ESMFs. The CTMF is a subset of the ESMF. Please refer to
    the topology drawings for further information about the network structures.
  title: CTMF
  version: 1.0.0
servers:
- url: "{protocol}://{apiRoot}/v1"
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    apiRoot:
      default: localhost:8080
      description: The server to use
paths:
  /auth:
    description: Endpoint to manage authentication tokens
    post:
      description: "Issues a new authentication token in exchange for credentials.\
        \ Currently requires no credentials, this is up to future implementations."
      operationId: auth_post
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: The authentication token as string
        "403":
          description: Wrong credentials were specified
      tags:
      - Authentication
      x-openapi-router-controller: ctmf_server.controllers.authentication_controller
    summary: Manages authentication towards this service
  /tunnel_deployment:
    delete:
      description: Deletes a tunnel from this domain
      operationId: tunnel_deployment_delete
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the tunnel to be deleted.
        explode: true
        in: query
        name: tunnel_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The tunnel was successfully deleted.
        "403":
          description: Invalid or insufficient authentication provided.
        "404":
          description: The tunnel could not be found.
      tags:
      - Tunnel Synchronization
      x-openapi-router-controller: ctmf_server.controllers.tunnel_synchronization_controller
    description: Endpoint to deploy tunnels on this domain
    get:
      description: Lists all current tunnels issued by the requesting ESMF. Used for
        synchronization purposes.
      operationId: tunnel_deployment_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tunnel'
                type: array
          description: The current list of tunnels assigned to this ESMF.
        "403":
          description: Invalid authentication provided
      tags:
      - Tunnel Synchronization
      x-openapi-router-controller: ctmf_server.controllers.tunnel_synchronization_controller
    put:
      description: Creates a new tunnel on this domain
      operationId: tunnel_deployment_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the tunnel to be deployed.
        explode: true
        in: query
        name: tunnel_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The tunnel has been deployed or altered
        "403":
          description: Invalid or insufficient authentication provided
        "404":
          description: The tunnel reservation could not be found
      tags:
      - Tunnel Synchronization
      x-openapi-router-controller: ctmf_server.controllers.tunnel_synchronization_controller
    summary: Manages tunnel deployments within the two-phase commit protocol between
      ESMFs
  /tunnel_reservation:
    delete:
      description: Deletes a tunnel reservation
      operationId: tunnel_reservation_delete
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      - description: The id of the tunnel reservation to be deleted.
        explode: true
        in: query
        name: tunnel_id
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          description: The tunnel reservation was successfully deleted.
        "403":
          description: Invalid or insufficient authentication provided.
        "404":
          description: The tunnel reservation could not be found.
      tags:
      - Tunnel Synchronization
      x-openapi-router-controller: ctmf_server.controllers.tunnel_synchronization_controller
    description: Endpoint to reserve tunnel capacity on this domain
    get:
      description: Lists all current tunnel reservations issued by the requesting
        ESMF. Used for synchronization purposes.
      operationId: tunnel_reservation_get
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tunnel'
                type: array
          description: The current list of tunnel reservations assigned to this ESMF.
        "403":
          description: Invalid authentication provided
      tags:
      - Tunnel Synchronization
      x-openapi-router-controller: ctmf_server.controllers.tunnel_synchronization_controller
    put:
      description: Creates a new tunnel reservation on this domain
      operationId: tunnel_reservation_put
      parameters:
      - description: The authentication token issued by prior login
        explode: true
        in: query
        name: auth
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tunnel'
        description: The tunnel to reserve or alter.
        x-body-name: body
      responses:
        "200":
          description: The tunnel has been reserved.
        "403":
          description: Invalid or insufficient authentication provided
        "404":
          description: The input or output could not be found
        "409":
          description: A tunnel with this id already exists and source or target do
            not match
        "507":
          description: Insufficient resources by participating domain or requester
      tags:
      - Tunnel Synchronization
      x-openapi-router-controller: ctmf_server.controllers.tunnel_synchronization_controller
      x-codegen-request-body-name: body
    summary: Manages tunnel reservations within the two-phase commit protocol between
      ESMFs and CTMFs
components:
  schemas:
    tunnel:
      example:
        burst_rate: 5
        latency: 5
        max_rate: 1
        from:
          port: 2
          ip: ip
          transport_protocol: UDP
          mac: mac
        id: 0
        to:
          port: 2
          ip: ip
          transport_protocol: UDP
          mac: mac
        min_rate: 6
      properties:
        id:
          description: The tunnel identifier
          format: int32
          title: id
          type: integer
        min_rate:
          description: The minimum transmission rate as bits/s
          format: int64
          title: min_rate
          type: integer
        max_rate:
          description: The maximum transmission rate as bits/s
          format: int64
          title: max_rate
          type: integer
        burst_rate:
          description: The burst transmission rate as bits/s
          format: int64
          title: burst_rate
          type: integer
        latency:
          description: The required maximum latency
          format: int16
          title: latency
          type: integer
        from:
          $ref: '#/components/schemas/endpoint'
        to:
          $ref: '#/components/schemas/endpoint'
      title: tunnel
      type: object
    endpoint:
      description: Specifying an endpoint to be matched for source or target
      example:
        port: 2
        ip: ip
        transport_protocol: UDP
        mac: mac
      properties:
        transport_protocol:
          description: The protocol to be expected
          enum:
          - UDP
          - TCP
          title: transport_protocol
          type: string
        ip:
          description: Specifies the source or target ip to be matched. Leave empty
            for no matching.
          title: ip
          type: string
        mac:
          description: Specifies the source or target mac to be matched. Leave empty
            for no matching.
          title: mac
          type: string
        port:
          default: 0
          description: Specifies the source or target port to be matched. Leave empty
            or on 0 for no matching.
          format: i16
          title: port
          type: integer
      title: endpoint
      type: object
