# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from esmf_server.models.base_model_ import Model
from esmf_server import util


class DomainConfigurationTunnelIdRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fr: int=None, to: int=None):
        """DomainConfigurationTunnelIdRange - a model defined in OpenAPI

        :param fr: The fr of this DomainConfigurationTunnelIdRange.
        :param to: The to of this DomainConfigurationTunnelIdRange.
        """
        self.openapi_types = {
            'fr': int,
            'to': int
        }

        self.attribute_map = {
            'fr': 'fr',
            'to': 'to'
        }

        self._fr = fr
        self._to = to

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DomainConfigurationTunnelIdRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The domain_configuration_tunnel_id_range of this DomainConfigurationTunnelIdRange.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fr(self):
        """Gets the fr of this DomainConfigurationTunnelIdRange.

        Lower bound of this range (inclusive)

        :return: The fr of this DomainConfigurationTunnelIdRange.
        :rtype: int
        """
        return self._fr

    @fr.setter
    def fr(self, fr):
        """Sets the fr of this DomainConfigurationTunnelIdRange.

        Lower bound of this range (inclusive)

        :param fr: The fr of this DomainConfigurationTunnelIdRange.
        :type fr: int
        """

        self._fr = fr

    @property
    def to(self):
        """Gets the to of this DomainConfigurationTunnelIdRange.

        Higher bound of this range (exclusive)

        :return: The to of this DomainConfigurationTunnelIdRange.
        :rtype: int
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this DomainConfigurationTunnelIdRange.

        Higher bound of this range (exclusive)

        :param to: The to of this DomainConfigurationTunnelIdRange.
        :type to: int
        """

        self._to = to
