# coding: utf-8

# flake8: noqa

"""
    CTMF

    A simple API to interact with the Core Tunnel Management Function. Supports creating and removing tunnels on this domains. Is advised to allocate resources by external ESMFs. The CTMF is a subset of the ESMF. Please refer to the topology drawings for further information about the network structures.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from ctmf_client.api_client import ApiClient

# import Configuration
from ctmf_client.configuration import Configuration

# import exceptions
from ctmf_client.exceptions import OpenApiException
from ctmf_client.exceptions import ApiAttributeError
from ctmf_client.exceptions import ApiTypeError
from ctmf_client.exceptions import ApiValueError
from ctmf_client.exceptions import ApiKeyError
from ctmf_client.exceptions import ApiException
