# coding: utf-8

"""
    VPN Gateway API

    A simple API to manage tunnel entries on a dedicated host within the edges. The VPN Gateway is used to encrypt traffic before it enters the first black network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import vpn_gateway_client
from vpn_gateway_client.model.tunnel_entry import TunnelEntry
from vpn_gateway_client import configuration


class TestTunnelEntry(unittest.TestCase):
    """TunnelEntry unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
