# coding: utf-8

"""
    VPN Gateway API

    A simple API to manage tunnel entries on a dedicated host within the edges. The VPN Gateway is used to encrypt traffic before it enters the first black network.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vpn_gateway_client import schemas  # noqa: F401


class TunnelEntry(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            tunnel_entry_id = schemas.Int32Schema
            inner_subnet = schemas.StrSchema
            local_port = schemas.IntSchema
            remote_end = schemas.StrSchema
            private_key = schemas.StrSchema
            public_key = schemas.StrSchema
            local_tunnel_ip = schemas.StrSchema
            remote_tunnel_ip = schemas.StrSchema
            
            
            class ingress_matches(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            class properties:
                                intf_name = schemas.StrSchema
                                slice_id = schemas.IntSchema
                                __annotations__ = {
                                    "intf_name": intf_name,
                                    "slice_id": slice_id,
                                }
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["intf_name"]) -> MetaOapg.properties.intf_name: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["slice_id"]) -> MetaOapg.properties.slice_id: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["intf_name", "slice_id", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["intf_name"]) -> typing.Union[MetaOapg.properties.intf_name, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["slice_id"]) -> typing.Union[MetaOapg.properties.slice_id, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["intf_name", "slice_id", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, ],
                            intf_name: typing.Union[MetaOapg.properties.intf_name, str, schemas.Unset] = schemas.unset,
                            slice_id: typing.Union[MetaOapg.properties.slice_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                *_args,
                                intf_name=intf_name,
                                slice_id=slice_id,
                                _configuration=_configuration,
                                **kwargs,
                            )
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]], typing.List[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'ingress_matches':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class egress_matches(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            class properties:
                                intf_name = schemas.StrSchema
                                slice_id = schemas.IntSchema
                                __annotations__ = {
                                    "intf_name": intf_name,
                                    "slice_id": slice_id,
                                }
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["intf_name"]) -> MetaOapg.properties.intf_name: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["slice_id"]) -> MetaOapg.properties.slice_id: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["intf_name", "slice_id", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["intf_name"]) -> typing.Union[MetaOapg.properties.intf_name, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["slice_id"]) -> typing.Union[MetaOapg.properties.slice_id, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["intf_name", "slice_id", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *_args: typing.Union[dict, frozendict.frozendict, ],
                            intf_name: typing.Union[MetaOapg.properties.intf_name, str, schemas.Unset] = schemas.unset,
                            slice_id: typing.Union[MetaOapg.properties.slice_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                *_args,
                                intf_name=intf_name,
                                slice_id=slice_id,
                                _configuration=_configuration,
                                **kwargs,
                            )
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]], typing.List[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'egress_matches':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "tunnel_entry_id": tunnel_entry_id,
                "inner_subnet": inner_subnet,
                "local_port": local_port,
                "remote_end": remote_end,
                "private_key": private_key,
                "public_key": public_key,
                "local_tunnel_ip": local_tunnel_ip,
                "remote_tunnel_ip": remote_tunnel_ip,
                "ingress_matches": ingress_matches,
                "egress_matches": egress_matches,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tunnel_entry_id"]) -> MetaOapg.properties.tunnel_entry_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inner_subnet"]) -> MetaOapg.properties.inner_subnet: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["local_port"]) -> MetaOapg.properties.local_port: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remote_end"]) -> MetaOapg.properties.remote_end: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["private_key"]) -> MetaOapg.properties.private_key: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public_key"]) -> MetaOapg.properties.public_key: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["local_tunnel_ip"]) -> MetaOapg.properties.local_tunnel_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remote_tunnel_ip"]) -> MetaOapg.properties.remote_tunnel_ip: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ingress_matches"]) -> MetaOapg.properties.ingress_matches: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["egress_matches"]) -> MetaOapg.properties.egress_matches: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tunnel_entry_id", "inner_subnet", "local_port", "remote_end", "private_key", "public_key", "local_tunnel_ip", "remote_tunnel_ip", "ingress_matches", "egress_matches", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tunnel_entry_id"]) -> typing.Union[MetaOapg.properties.tunnel_entry_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inner_subnet"]) -> typing.Union[MetaOapg.properties.inner_subnet, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["local_port"]) -> typing.Union[MetaOapg.properties.local_port, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remote_end"]) -> typing.Union[MetaOapg.properties.remote_end, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["private_key"]) -> typing.Union[MetaOapg.properties.private_key, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public_key"]) -> typing.Union[MetaOapg.properties.public_key, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["local_tunnel_ip"]) -> typing.Union[MetaOapg.properties.local_tunnel_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remote_tunnel_ip"]) -> typing.Union[MetaOapg.properties.remote_tunnel_ip, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ingress_matches"]) -> typing.Union[MetaOapg.properties.ingress_matches, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["egress_matches"]) -> typing.Union[MetaOapg.properties.egress_matches, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tunnel_entry_id", "inner_subnet", "local_port", "remote_end", "private_key", "public_key", "local_tunnel_ip", "remote_tunnel_ip", "ingress_matches", "egress_matches", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        tunnel_entry_id: typing.Union[MetaOapg.properties.tunnel_entry_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        inner_subnet: typing.Union[MetaOapg.properties.inner_subnet, str, schemas.Unset] = schemas.unset,
        local_port: typing.Union[MetaOapg.properties.local_port, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        remote_end: typing.Union[MetaOapg.properties.remote_end, str, schemas.Unset] = schemas.unset,
        private_key: typing.Union[MetaOapg.properties.private_key, str, schemas.Unset] = schemas.unset,
        public_key: typing.Union[MetaOapg.properties.public_key, str, schemas.Unset] = schemas.unset,
        local_tunnel_ip: typing.Union[MetaOapg.properties.local_tunnel_ip, str, schemas.Unset] = schemas.unset,
        remote_tunnel_ip: typing.Union[MetaOapg.properties.remote_tunnel_ip, str, schemas.Unset] = schemas.unset,
        ingress_matches: typing.Union[MetaOapg.properties.ingress_matches, list, tuple, schemas.Unset] = schemas.unset,
        egress_matches: typing.Union[MetaOapg.properties.egress_matches, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TunnelEntry':
        return super().__new__(
            cls,
            *_args,
            tunnel_entry_id=tunnel_entry_id,
            inner_subnet=inner_subnet,
            local_port=local_port,
            remote_end=remote_end,
            private_key=private_key,
            public_key=public_key,
            local_tunnel_ip=local_tunnel_ip,
            remote_tunnel_ip=remote_tunnel_ip,
            ingress_matches=ingress_matches,
            egress_matches=egress_matches,
            _configuration=_configuration,
            **kwargs,
        )
