# coding: utf-8

# flake8: noqa

"""
    DSMF

    A simple API to interact with the Domain Slice Management Function. Supports reserving, creating and removing slices and tunnels from one external domain to another external domain or host. Please refer to the topology drawings for further information about the network structures.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from dsmf_client.api_client import ApiClient

# import Configuration
from dsmf_client.configuration import Configuration

# import exceptions
from dsmf_client.exceptions import OpenApiException
from dsmf_client.exceptions import ApiAttributeError
from dsmf_client.exceptions import ApiTypeError
from dsmf_client.exceptions import ApiValueError
from dsmf_client.exceptions import ApiKeyError
from dsmf_client.exceptions import ApiException
